
export const GET_ESTIMATIVAS = 'GET_ESTIMATIVAS';
export const GET_ESTIMATIVASANO = 'GET_ESTIMATIVASANO';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const UPDATE_ESTIMATIVA = 'UPDATE_LOG';
export const CLEAR_ESTIMATIVAS = 'CLEAR_ESTIMATIVAS';
export const SET_LOADING = 'SET_LOADING';
export const ESTIMATIVAS_ERROR = 'ESTIMATIVAS_ERROR';
export const SEARCH_ESTIMATIVAS = 'SEARCH_ESTIMATIVAS';
